#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="${ROOT_DIR}/backend"

if [[ -z "${CHILD_AI_MIMO_API_KEY:-}" ]]; then
  echo "REAL_PATH_BACKEND: BLOCKED"
  echo "reason=missing CHILD_AI_MIMO_API_KEY"
  echo "Set CHILD_AI_MIMO_API_KEY in your shell; do not write it to .env or git."
  exit 2
fi

export CHILD_AI_MODEL_PROVIDER="${CHILD_AI_MODEL_PROVIDER:-mimo}"
export CHILD_AI_CHILD_CHAT_PROFILE="${CHILD_AI_CHILD_CHAT_PROFILE:-mimo_child_chat}"
export CHILD_AI_MIMO_MODEL="${CHILD_AI_MIMO_MODEL:-mimo-v2.5-pro}"
export CHILD_AI_VISION_PROVIDER="${CHILD_AI_VISION_PROVIDER:-mimo}"
export CHILD_AI_VISION_PROFILE="${CHILD_AI_VISION_PROFILE:-mimo_vision}"
export CHILD_AI_MIMO_VISION_MODEL="${CHILD_AI_MIMO_VISION_MODEL:-mimo-v2.5}"
export CHILD_AI_MIMO_OCR_MODEL="${CHILD_AI_MIMO_OCR_MODEL:-${CHILD_AI_MIMO_VISION_MODEL}}"
export CHILD_AI_MIMO_ENABLED="${CHILD_AI_MIMO_ENABLED:-true}"
export CHILD_AI_MIMO_ALLOW_CHILD_DATA="${CHILD_AI_MIMO_ALLOW_CHILD_DATA:-true}"
export CHILD_AI_MIMO_ALLOW_IMAGE="${CHILD_AI_MIMO_ALLOW_IMAGE:-true}"
export CHILD_AI_MIMO_RETENTION_POLICY_CHECKED="${CHILD_AI_MIMO_RETENTION_POLICY_CHECKED:-true}"
export CHILD_AI_MODEL_DEBUG_TRACE_FULL_TEXT="${CHILD_AI_MODEL_DEBUG_TRACE_FULL_TEXT:-true}"
export CHILD_AI_ASR_PROVIDER="${CHILD_AI_ASR_PROVIDER:-local_sensevoice}"
export CHILD_AI_LOCAL_SENSEVOICE_ENABLED="${CHILD_AI_LOCAL_SENSEVOICE_ENABLED:-true}"
export CHILD_AI_ASR_FALLBACK_PROVIDER="${CHILD_AI_ASR_FALLBACK_PROVIDER:-mimo}"
export CHILD_AI_TTS_PROVIDER="${CHILD_AI_TTS_PROVIDER:-mimo}"
export CHILD_AI_MIMO_TTS_ENABLED="${CHILD_AI_MIMO_TTS_ENABLED:-true}"

cd "${BACKEND_DIR}"
echo "REAL_PATH_BACKEND: starting"
echo "child_chat_model=${CHILD_AI_MIMO_MODEL}"
echo "vision_model=${CHILD_AI_MIMO_VISION_MODEL}"
cd "${ROOT_DIR}"
exec bash "${ROOT_DIR}/scripts/start_backend_services.sh" \
  --foreground \
  --agent "${CODEX_AGENT_NAME:-real-path}" \
  --host "${CHILD_AI_BACKEND_HOST:-0.0.0.0}" \
  --port "${CHILD_AI_BACKEND_PORT:-8000}"
